from abc import ABC, abstractmethod
from typing import List, Optional
from app.api.schemas.internal import NeedRecord

class BaseNeedsRepository(ABC):
    @abstractmethod
    def save_all(self, needs: List[NeedRecord]) -> None:
        """
        Persists a list of needs. Expected to be idempotent for a given assessment_id.
        """
        pass

    @abstractmethod
    def get_by_incident(self, incident_id: str) -> List[NeedRecord]:
        """
        Retrieves all needs associated with an incident.
        """
        pass
        
    @abstractmethod
    def get_by_assessment(self, assessment_id: str) -> List[NeedRecord]:
        """
        Retrieves all needs generated by a specific assessment.
        """
        pass

class InMemoryNeedsRepository(BaseNeedsRepository):
    def __init__(self):
        self._needs: dict[str, NeedRecord] = {}

    def save_all(self, needs: List[NeedRecord]) -> None:
        if not needs:
            return
            
        assessment_id = needs[0].assessment_id
        
        # Idempotency check: if needs for this assessment already exist, ignore (immutable snapshot)
        if assessment_id:
            existing_for_assessment = [n for n in self._needs.values() if n.assessment_id == assessment_id]
            if existing_for_assessment:
                return
                
        for need in needs:
            self._needs[need.need_id] = need

    def get_by_incident(self, incident_id: str) -> List[NeedRecord]:
        return [n for n in self._needs.values() if n.incident_id == incident_id]

    def get_by_assessment(self, assessment_id: str) -> List[NeedRecord]:
        return [n for n in self._needs.values() if n.assessment_id == assessment_id]
