-- supabase/migrations/001_initial_ps20_schema.sql

-- Enable UUID extension
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- TABLE: reports
-- Stores raw incoming disaster reports
CREATE TABLE IF NOT EXISTS public.reports (
    report_id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    source TEXT NOT NULL,
    source_record_id TEXT NOT NULL,
    source_url TEXT,
    reported_at TIMESTAMPTZ,
    ingested_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    hazard_type TEXT NOT NULL,
    hazard_subtype TEXT,
    latitude DOUBLE PRECISION,
    longitude DOUBLE PRECISION,
    location_name TEXT,
    country TEXT,
    administrative_area TEXT,
    magnitude DOUBLE PRECISION,
    intensity DOUBLE PRECISION,
    depth DOUBLE PRECISION,
    wind_speed DOUBLE PRECISION,
    pressure DOUBLE PRECISION,
    affected_population INTEGER,
    damage_estimate DOUBLE PRECISION,
    raw_text TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UNIQUE(source, source_record_id)
);

-- TABLE: incidents
-- Stores verified/synthesized disaster incidents
CREATE TABLE IF NOT EXISTS public.incidents (
    incident_id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    hazard_type TEXT NOT NULL,
    status TEXT NOT NULL DEFAULT 'CANDIDATE',
    centroid_latitude DOUBLE PRECISION,
    centroid_longitude DOUBLE PRECISION,
    first_observed_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- TABLE: incident_evidence
-- Maps reports to incidents
CREATE TABLE IF NOT EXISTS public.incident_evidence (
    evidence_id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    incident_id UUID NOT NULL REFERENCES public.incidents(incident_id) ON DELETE CASCADE,
    report_id UUID NOT NULL REFERENCES public.reports(report_id) ON DELETE CASCADE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UNIQUE(incident_id, report_id)
);

-- TABLE: assessments
-- Persists the output of the situation assessment pipeline
CREATE TABLE IF NOT EXISTS public.assessments (
    assessment_id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    incident_id UUID NOT NULL REFERENCES public.incidents(incident_id) ON DELETE CASCADE,
    verification_status TEXT,
    severity_status TEXT,
    severity JSONB, -- Stores the predictor dictionary output
    trajectory_status TEXT,
    trajectory JSONB,
    priority_level TEXT,
    priority_score DOUBLE PRECISION,
    policy_version TEXT,
    assessed_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- TABLE: needs
-- Persists calculated resource requirements from ML
CREATE TABLE IF NOT EXISTS public.needs (
    need_id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    incident_id UUID NOT NULL REFERENCES public.incidents(incident_id) ON DELETE CASCADE,
    assessment_id UUID REFERENCES public.assessments(assessment_id) ON DELETE SET NULL,
    resource_type TEXT NOT NULL,
    category TEXT,
    quantity DOUBLE PRECISION NOT NULL,
    unit TEXT NOT NULL,
    urgency TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- TABLE: resources
-- Represents available operational resources for GLOP allocation
CREATE TABLE IF NOT EXISTS public.resources (
    resource_id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    location_id TEXT NOT NULL,
    resource_type TEXT NOT NULL,
    category TEXT,
    quantity_available DOUBLE PRECISION NOT NULL DEFAULT 0.0,
    unit TEXT NOT NULL,
    provenance JSONB,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- TABLE: allocations
-- Persists actual OR-Tools allocation results
CREATE TABLE IF NOT EXISTS public.allocations (
    allocation_id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    optimization_run_id TEXT NOT NULL,
    incident_id UUID NOT NULL REFERENCES public.incidents(incident_id) ON DELETE CASCADE,
    requirement_id TEXT, -- Might link to a need_id externally if string maps match
    source_location_id TEXT NOT NULL,
    resource_type TEXT NOT NULL,
    category TEXT,
    unit TEXT NOT NULL,
    quantity_allocated DOUBLE PRECISION NOT NULL,
    quantity_requested DOUBLE PRECISION NOT NULL,
    quantity_unmet DOUBLE PRECISION NOT NULL,
    priority_score DOUBLE PRECISION,
    solver_status TEXT,
    explanation TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- TABLE: actions
-- Operational actions generated by LangGraph coordination
CREATE TABLE IF NOT EXISTS public.actions (
    action_id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    incident_id UUID NOT NULL REFERENCES public.incidents(incident_id) ON DELETE CASCADE,
    action_type TEXT NOT NULL,
    status TEXT NOT NULL DEFAULT 'PROPOSED',
    description TEXT,
    source_decision_id TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- TABLE: approvals
-- Supports human-in-the-loop review
CREATE TABLE IF NOT EXISTS public.approvals (
    approval_id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    incident_id UUID NOT NULL REFERENCES public.incidents(incident_id) ON DELETE CASCADE,
    action_id UUID REFERENCES public.actions(action_id) ON DELETE CASCADE,
    status TEXT NOT NULL DEFAULT 'PENDING',
    reviewer_id TEXT, -- Nullable since auth is not implemented
    reason TEXT,
    decided_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- TABLE: audit_events
-- Immutable operational audit trail
CREATE TABLE IF NOT EXISTS public.audit_events (
    event_id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    event_type TEXT NOT NULL,
    incident_id UUID REFERENCES public.incidents(incident_id) ON DELETE SET NULL,
    report_id UUID REFERENCES public.reports(report_id) ON DELETE SET NULL,
    actor_type TEXT NOT NULL,
    actor_reference TEXT,
    payload JSONB,
    correlation_id TEXT,
    event_timestamp TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- INDEXES
CREATE INDEX IF NOT EXISTS idx_reports_source_record ON public.reports(source, source_record_id);
CREATE INDEX IF NOT EXISTS idx_reports_hazard_type ON public.reports(hazard_type);
CREATE INDEX IF NOT EXISTS idx_incidents_status ON public.incidents(status);
CREATE INDEX IF NOT EXISTS idx_incidents_hazard_type ON public.incidents(hazard_type);
CREATE INDEX IF NOT EXISTS idx_assessments_incident_id ON public.assessments(incident_id);
CREATE INDEX IF NOT EXISTS idx_needs_incident_resource ON public.needs(incident_id, resource_type);
CREATE INDEX IF NOT EXISTS idx_allocations_optimization_run ON public.allocations(optimization_run_id);
CREATE INDEX IF NOT EXISTS idx_allocations_incident_id ON public.allocations(incident_id);
CREATE INDEX IF NOT EXISTS idx_audit_events_incident ON public.audit_events(incident_id);
CREATE INDEX IF NOT EXISTS idx_audit_events_type ON public.audit_events(event_type);

-- ROW LEVEL SECURITY (RLS)
-- Explicitly enable RLS on all tables.
-- Because authentication is not yet implemented on the frontend,
-- and the FastAPI server acts as a privileged service role,
-- we do NOT create public policies. The service-role key will bypass RLS.
-- This ensures the DB is closed to the public internet natively.
ALTER TABLE public.reports ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.incidents ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.incident_evidence ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.assessments ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.needs ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.resources ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.allocations ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.actions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.approvals ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.audit_events ENABLE ROW LEVEL SECURITY;
