-- ==========================================
-- supabase/migrations/001_initial_ps20_schema.sql
-- ==========================================
-- supabase/migrations/001_initial_ps20_schema.sql

-- Enable UUID extension
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- TABLE: reports
-- Stores raw incoming disaster reports
CREATE TABLE IF NOT EXISTS public.reports (
    report_id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    source TEXT NOT NULL,
    source_record_id TEXT NOT NULL,
    source_url TEXT,
    reported_at TIMESTAMPTZ,
    ingested_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    hazard_type TEXT NOT NULL,
    hazard_subtype TEXT,
    latitude DOUBLE PRECISION,
    longitude DOUBLE PRECISION,
    location_name TEXT,
    country TEXT,
    administrative_area TEXT,
    magnitude DOUBLE PRECISION,
    intensity DOUBLE PRECISION,
    depth DOUBLE PRECISION,
    wind_speed DOUBLE PRECISION,
    pressure DOUBLE PRECISION,
    affected_population INTEGER,
    damage_estimate DOUBLE PRECISION,
    raw_text TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UNIQUE(source, source_record_id)
);

-- TABLE: incidents
-- Stores verified/synthesized disaster incidents
CREATE TABLE IF NOT EXISTS public.incidents (
    incident_id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    hazard_type TEXT NOT NULL,
    status TEXT NOT NULL DEFAULT 'CANDIDATE',
    centroid_latitude DOUBLE PRECISION,
    centroid_longitude DOUBLE PRECISION,
    first_observed_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- TABLE: incident_evidence
-- Maps reports to incidents
CREATE TABLE IF NOT EXISTS public.incident_evidence (
    evidence_id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    incident_id UUID NOT NULL REFERENCES public.incidents(incident_id) ON DELETE CASCADE,
    report_id UUID NOT NULL REFERENCES public.reports(report_id) ON DELETE CASCADE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UNIQUE(incident_id, report_id)
);

-- TABLE: assessments
-- Persists the output of the situation assessment pipeline
CREATE TABLE IF NOT EXISTS public.assessments (
    assessment_id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    incident_id UUID NOT NULL REFERENCES public.incidents(incident_id) ON DELETE CASCADE,
    verification_status TEXT,
    severity_status TEXT,
    severity JSONB, -- Stores the predictor dictionary output
    trajectory_status TEXT,
    trajectory JSONB,
    priority_level TEXT,
    priority_score DOUBLE PRECISION,
    policy_version TEXT,
    assessed_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- TABLE: needs
-- Persists calculated resource requirements from ML
CREATE TABLE IF NOT EXISTS public.needs (
    need_id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    incident_id UUID NOT NULL REFERENCES public.incidents(incident_id) ON DELETE CASCADE,
    assessment_id UUID REFERENCES public.assessments(assessment_id) ON DELETE SET NULL,
    resource_type TEXT NOT NULL,
    category TEXT,
    quantity DOUBLE PRECISION NOT NULL,
    unit TEXT NOT NULL,
    urgency TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- TABLE: resources
-- Represents available operational resources for GLOP allocation
CREATE TABLE IF NOT EXISTS public.resources (
    resource_id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    location_id TEXT NOT NULL,
    resource_type TEXT NOT NULL,
    category TEXT,
    quantity_available DOUBLE PRECISION NOT NULL DEFAULT 0.0,
    unit TEXT NOT NULL,
    provenance JSONB,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- TABLE: allocations
-- Persists actual OR-Tools allocation results
CREATE TABLE IF NOT EXISTS public.allocations (
    allocation_id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    optimization_run_id TEXT NOT NULL,
    incident_id UUID NOT NULL REFERENCES public.incidents(incident_id) ON DELETE CASCADE,
    requirement_id TEXT, -- Might link to a need_id externally if string maps match
    source_location_id TEXT NOT NULL,
    resource_type TEXT NOT NULL,
    category TEXT,
    unit TEXT NOT NULL,
    quantity_allocated DOUBLE PRECISION NOT NULL,
    quantity_requested DOUBLE PRECISION NOT NULL,
    quantity_unmet DOUBLE PRECISION NOT NULL,
    priority_score DOUBLE PRECISION,
    solver_status TEXT,
    explanation TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- TABLE: actions
-- Operational actions generated by LangGraph coordination
CREATE TABLE IF NOT EXISTS public.actions (
    action_id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    incident_id UUID NOT NULL REFERENCES public.incidents(incident_id) ON DELETE CASCADE,
    action_type TEXT NOT NULL,
    status TEXT NOT NULL DEFAULT 'PROPOSED',
    description TEXT,
    source_decision_id TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- TABLE: approvals
-- Supports human-in-the-loop review
CREATE TABLE IF NOT EXISTS public.approvals (
    approval_id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    incident_id UUID NOT NULL REFERENCES public.incidents(incident_id) ON DELETE CASCADE,
    action_id UUID REFERENCES public.actions(action_id) ON DELETE CASCADE,
    status TEXT NOT NULL DEFAULT 'PENDING',
    reviewer_id TEXT, -- Nullable since auth is not implemented
    reason TEXT,
    decided_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- TABLE: audit_events
-- Immutable operational audit trail
CREATE TABLE IF NOT EXISTS public.audit_events (
    event_id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    event_type TEXT NOT NULL,
    incident_id UUID REFERENCES public.incidents(incident_id) ON DELETE SET NULL,
    report_id UUID REFERENCES public.reports(report_id) ON DELETE SET NULL,
    actor_type TEXT NOT NULL,
    actor_reference TEXT,
    payload JSONB,
    correlation_id TEXT,
    event_timestamp TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- INDEXES
CREATE INDEX IF NOT EXISTS idx_reports_source_record ON public.reports(source, source_record_id);
CREATE INDEX IF NOT EXISTS idx_reports_hazard_type ON public.reports(hazard_type);
CREATE INDEX IF NOT EXISTS idx_incidents_status ON public.incidents(status);
CREATE INDEX IF NOT EXISTS idx_incidents_hazard_type ON public.incidents(hazard_type);
CREATE INDEX IF NOT EXISTS idx_assessments_incident_id ON public.assessments(incident_id);
CREATE INDEX IF NOT EXISTS idx_needs_incident_resource ON public.needs(incident_id, resource_type);
CREATE INDEX IF NOT EXISTS idx_allocations_optimization_run ON public.allocations(optimization_run_id);
CREATE INDEX IF NOT EXISTS idx_allocations_incident_id ON public.allocations(incident_id);
CREATE INDEX IF NOT EXISTS idx_audit_events_incident ON public.audit_events(incident_id);
CREATE INDEX IF NOT EXISTS idx_audit_events_type ON public.audit_events(event_type);

-- ROW LEVEL SECURITY (RLS)
-- Explicitly enable RLS on all tables.
-- Because authentication is not yet implemented on the frontend,
-- and the FastAPI server acts as a privileged service role,
-- we do NOT create public policies. The service-role key will bypass RLS.
-- This ensures the DB is closed to the public internet natively.
ALTER TABLE public.reports ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.incidents ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.incident_evidence ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.assessments ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.needs ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.resources ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.allocations ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.actions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.approvals ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.audit_events ENABLE ROW LEVEL SECURITY;


-- ==========================================
-- supabase/migrations/002_assessment_idempotency_and_provenance.sql
-- ==========================================
-- supabase/migrations/002_assessment_idempotency_and_provenance.sql

-- Add idempotency constraint
ALTER TABLE public.assessments 
ADD COLUMN idempotency_key TEXT;

-- Create unique constraint for incident_id + idempotency_key
CREATE UNIQUE INDEX idx_assessments_idempotency 
ON public.assessments (incident_id, idempotency_key) 
WHERE idempotency_key IS NOT NULL;

-- Drop generic policy_version
ALTER TABLE public.assessments 
DROP COLUMN IF EXISTS policy_version;

-- Add structured provenance fields
ALTER TABLE public.assessments ADD COLUMN severity_model_version TEXT;
ALTER TABLE public.assessments ADD COLUMN verification_policy_version TEXT;
ALTER TABLE public.assessments ADD COLUMN trajectory_policy_version TEXT;
ALTER TABLE public.assessments ADD COLUMN needs_policy_version TEXT;
ALTER TABLE public.assessments ADD COLUMN priority_policy_version TEXT;


-- ==========================================
-- supabase/migrations/003_needs_resources_persistence.sql
-- ==========================================
-- supabase/migrations/003_needs_resources_persistence.sql

-- 1. Modify `needs` table to align with ML schema ResourceRequirement
ALTER TABLE public.needs ALTER COLUMN quantity DROP NOT NULL;
ALTER TABLE public.needs ALTER COLUMN unit DROP NOT NULL;

ALTER TABLE public.needs ADD COLUMN status TEXT;
ALTER TABLE public.needs ADD COLUMN time_window TEXT;
ALTER TABLE public.needs ADD COLUMN rule_id TEXT;
ALTER TABLE public.needs ADD COLUMN policy_version TEXT;
ALTER TABLE public.needs ADD COLUMN calculation_basis JSONB;
ALTER TABLE public.needs ADD COLUMN provenance JSONB;
ALTER TABLE public.needs ADD COLUMN explanation TEXT;

-- 2. Modify `resources` table to enforce unique inventory tracking per location + category
CREATE UNIQUE INDEX idx_resources_location_type_category 
ON public.resources (location_id, resource_type, COALESCE(category, ''));



-- ==========================================
-- supabase/migrations/004_allocation_execution_identity.sql
-- ==========================================
-- supabase/migrations/004_allocation_execution_identity.sql

-- 1. Make optimization_run_id nullable to allow non-idempotent/ad-hoc executions
ALTER TABLE public.allocations
ALTER COLUMN optimization_run_id DROP NOT NULL;

-- 2. Add a partial unique index to enforce idempotency when an explicit run_id is supplied.
-- Multiple NULL executions for the same incident are allowed (not deduplicated).
-- Note: A single optimization execution might produce multiple allocation records for the same incident
-- (e.g., allocating multiple resources to different requirements). So uniqueness must include requirement_id 
-- or source_location_id + resource_type.
-- Looking at the idempotency requirement: "duplicate allocation decisions". 
-- If an orchestration run is retried, the batch of allocations should be ignored if already present.
-- We can't just put UNIQUE(incident_id, optimization_run_id) because one run inserts multiple rows.
-- The existing logic in SupabaseAllocationRepository checks if ANY row exists for optimization_run_id:
-- `self.client.table("allocations").select("allocation_id").eq("optimization_run_id", run_id).limit(1)`
-- So we don't necessarily need a multi-column UNIQUE constraint at the DB level, because 
-- the repository enforces it at the batch level before insert, and a single optimization run 
-- natively returns multiple rows. We should just keep the column nullable.

-- However, if we do want a unique constraint for each individual allocation within a run, it would be:
-- UNIQUE (optimization_run_id, requirement_id, source_location_id) WHERE optimization_run_id IS NOT NULL.
-- But since the repo handles batch existence checks, making the column nullable is sufficient to satisfy the requirements.


-- ==========================================
-- supabase/migrations/005_approval_optimization_run_id.sql
-- ==========================================
-- supabase/migrations/005_approval_optimization_run_id.sql

-- 1. Add optimization_run_id to approvals table to stably reference the allocation proposal
ALTER TABLE public.approvals
ADD COLUMN optimization_run_id TEXT;

-- 2. Relax the NOT NULL constraint on action_id since approvals will now track optimization runs (wait, it was already nullable, but let's be sure).
-- Wait, in 001, action_id is `action_id UUID REFERENCES public.actions(action_id) ON DELETE CASCADE`. So it's already nullable.
-- We will just make sure it's clear.

-- 3. Add an index to efficiently query approvals by optimization_run_id
CREATE INDEX IF NOT EXISTS idx_approvals_optimization_run_id ON public.approvals(optimization_run_id);


-- ==========================================
-- supabase/migrations/006_execution_action_metadata.sql
-- ==========================================
-- supabase/migrations/006_execution_action_metadata.sql

-- 1. Add execution metadata columns to public.actions table to capture Phase 4F execution records
ALTER TABLE public.actions
ADD COLUMN IF NOT EXISTS optimization_run_id TEXT,
ADD COLUMN IF NOT EXISTS approval_id UUID REFERENCES public.approvals(approval_id) ON DELETE SET NULL,
ADD COLUMN IF NOT EXISTS execution_id TEXT,
ADD COLUMN IF NOT EXISTS payload JSONB,
ADD COLUMN IF NOT EXISTS executed_by TEXT,
ADD COLUMN IF NOT EXISTS executed_at TIMESTAMPTZ;

-- 2. Indexes for fast lookup by execution_id and optimization_run_id
CREATE INDEX IF NOT EXISTS idx_actions_execution_id ON public.actions(execution_id);
CREATE INDEX IF NOT EXISTS idx_actions_optimization_run_id ON public.actions(optimization_run_id);


-- ==========================================
-- supabase/migrations/007_reassessment_metadata.sql
-- ==========================================
-- supabase/migrations/007_reassessment_metadata.sql

-- 1. Add parent_assessment_id and reassessment_reason to public.assessments
ALTER TABLE public.assessments
ADD COLUMN IF NOT EXISTS parent_assessment_id UUID REFERENCES public.assessments(assessment_id) ON DELETE SET NULL,
ADD COLUMN IF NOT EXISTS reassessment_reason TEXT;

-- 2. Add index for parent_assessment_id
CREATE INDEX IF NOT EXISTS idx_assessments_parent_id ON public.assessments(parent_assessment_id);

-- 3. Add previous_optimization_run_id to public.allocations
ALTER TABLE public.allocations
ADD COLUMN IF NOT EXISTS previous_optimization_run_id TEXT;

-- 4. Add index for previous_optimization_run_id
CREATE INDEX IF NOT EXISTS idx_allocations_previous_run ON public.allocations(previous_optimization_run_id);


